import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Our Git - AI Generated GitHub Profiles",
  description:
    "Easily create a profile link generated by AI using your GitHub username. Share your personalized profile with others.",
  keywords: [
    "AI Profile",
    "GitHub Profile",
    "Profile Link",
    "our-git",
    "GitHub Username",
  ],
  authors: [{ name: "our-git", url: "https://your-website.com" }], // Replace with actual URL
  openGraph: {
    title: "our-git - AI Generated GitHub Profiles",
    description:
      "Create a personalized profile link based on your GitHub username using AI. Share your GitHub profile with ease.",
    siteName: "our-git",
    url: "https://your-website.com", // Replace with actual URL
    type: "website",
    images: [
      {
        url: "https://your-website.com/images/og-image.png", // Replace with actual image URL
        width: 1200,
        height: 630,
        alt: "our-git AI GitHub Profile",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "our-git - AI GitHub Profile",
    description:
      "Generate a GitHub profile link with AI based on your username.",
    images: ["https://your-website.com/images/twitter-image.png"], // Replace with actual image URL
  },
  robots: {
    index: true, // Allow indexing by search engines
    follow: true, // Allow following links
    noarchive: false, // Allow cached pages to be shown in search results
  },
  alternates: {
    canonical: "https://your-website.com", // Canonical URL to prevent duplicate content issues
  },
  icons: {
    icon: "https://api.iconify.design/ph:github-logo-duotone.svg?color=%23770954",
    apple:
      "https://api.iconify.design/ph:github-logo-duotone.svg?color=%23770954",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
